import datasets
from ...abstasks.AbsTaskRetrieval import AbsTaskRetrieval


class FEVERLongDocumentRetrieval(AbsTaskRetrieval):

    _EVAL_SPLIT = 'test'

    @property
    def description(self):
        return {
            'name': 'FEVERLongDocumentRetrieval',
            'hf_hub_name': 'fever',
            "description": (
                "FEVER (Fact Extraction and VERification) consists of 18,544 claims generated by altering sentences"
                " extracted from Wikipedia and subsequently verified without knowledge of the sentence they were"
                " derived from. This task takes claims which have supporting evidence as queries."
                " Whole Wikipedia articles are retrieved as documents. The task is limited to 1M documents and"
                " 4255 queries (claims)."
            ),
            "reference": "https://fever.ai/",
            "type": "Retrieval",
            "category": "s2p",
            "eval_splits": ["test"],
            "eval_langs": ["en"],
            "main_score": "ndcg_at_10",
        }

    def load_data(self, **kwargs):
        if self.data_loaded:
            return

        query_rows = datasets.load_dataset(self.description['hf_hub_name'], 'v1.0', split='paper_test')
        corpus_rows = datasets.load_dataset('wikipedia', '20220301.en', split='train')[:1_000_000]
        corpus_titles = [title.replace(' ', '_') for title in corpus_rows['title']]
        qrels_rows = [
            {'id': str(row['id']), 'evidence_wiki_url': row['evidence_wiki_url']}
            for row in query_rows
            if row['label'] == 'SUPPORTS' and row['evidence_wiki_url'] in corpus_titles
        ]
        q_ids = [r['id'] for r in qrels_rows]

        self.queries = {
            self._EVAL_SPLIT: {str(row['id']): row['claim'] for row in query_rows if str(row['id']) in q_ids}
        }
        self.corpus = {
            self._EVAL_SPLIT: {
                title.replace(' ', '_'): {'text': text}
                for title, text in zip(corpus_rows['title'], corpus_rows['text'])
            }
        }
        self.relevant_docs = {self._EVAL_SPLIT: {str(row['id']): {row['evidence_wiki_url']: 1} for row in qrels_rows}}

        self.data_loaded = True
